using System;
using System.Linq;

namespace Base16.ErrGen.Utils.Code;

internal sealed class CSharpCodeBuilder : CodeBuilder
{
    public static CSharpCodeBuilder NewFile()
    {
        var result = new CSharpCodeBuilder();

        result.AppendLine("// <auto-generated/>");
        result.AppendLine("#nullable enable");
        result.AppendLine();

        return result;
    }

    public IDisposable PushScope()
    {
        AppendLine("{");
        var disposeAction = PushIndent();
        return new DisposeAction(() =>
        {
            disposeAction.Dispose();
            AppendLine("}");
        });
    }

    public IDisposable PushScopeExpression(String? prefix = null)
    {
        AppendLine($"{prefix}{{");
        var disposeAction = PushIndent();
        return new DisposeAction(() =>
        {
            disposeAction.Dispose();
            AppendLine("};");
        });
    }

    public void AppendSummary(String? summary)
    {
        if (String.IsNullOrWhiteSpace(summary))
            return;

        AppendLine("/// <summary>");
        AppendLines(summary!.Split('\n').Select(x => "///     " + x.Trim()));
        AppendLine("/// </summary>");
    }
}
