// === UsesDefault.g.cs ===
// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

public partial record UsesDefault : global::TestNamespace.DefaultError
{

    private UsesDefault(string message) : base(message) { }


    /// <summary>
    ///     Creates a new <see cref="UsesDefault"/> with the message template:
    ///     <para>
    ///         <c>Default error</c>
    ///     </para>
    /// </summary>
    /// <returns>A new instance of <see cref="UsesDefault"/>.</returns>
    public static UsesDefault From()
    {
        var message = "Default error";

        return new UsesDefault(message)
        {
        };
    }
}

// === UsesExplicit.g.cs ===
// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

public partial record UsesExplicit
{

    private UsesExplicit(string message, global::System.Guid traceId) : base(message, traceId) { }


    /// <summary>
    ///     Creates a new <see cref="UsesExplicit"/> with the message template:
    ///     <para>
    ///         <c>Special error</c>
    ///     </para>
    /// </summary>
    /// <param name="traceId">The value passed to the base type constructor.</param>
    /// <returns>A new instance of <see cref="UsesExplicit"/>.</returns>
    public static UsesExplicit From(global::System.Guid traceId)
    {
        var message = "Special error";

        return new UsesExplicit(message, traceId)
        {
        };
    }
}
