// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

public partial record ManyArgsError
{
    public String Message { get; private init; } = default!;

    public String A { get; private init; } = default!;

    public String B { get; private init; } = default!;

    public String C { get; private init; } = default!;

    public String D { get; private init; } = default!;

    private ManyArgsError() { }


    /// <summary>
    ///     Creates a new <see cref="ManyArgsError"/> with the message template:
    ///     <para>
    ///         <c>{A:String} {B:String} {C:String} {D:String}</c>
    ///     </para>
    /// </summary>
    /// <param name="a">The value for the <c>{A}</c> placeholder.</param>
    /// <param name="b">The value for the <c>{B}</c> placeholder.</param>
    /// <param name="c">The value for the <c>{C}</c> placeholder.</param>
    /// <param name="d">The value for the <c>{D}</c> placeholder.</param>
    /// <returns>A new instance of <see cref="ManyArgsError"/>.</returns>
    public static ManyArgsError FromABCAndD(String a, String b, String c, String d)
    {
        var message = String.Concat(
            a,
            " ",
            b,
            " ",
            c,
            " ",
            d
        );

        return new ManyArgsError()
        {
            Message = message,
            A = a,
            B = b,
            C = c,
            D = d,
        };
    }
}
