// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

public partial record MyError : global::TestNamespace.TracedError
{
    public String Message { get; private init; } = default!;

    private MyError(global::System.Guid traceId) : base(traceId) { }


    /// <summary>
    ///     Creates a new <see cref="MyError"/> with the message template:
    ///     <para>
    ///         <c>Something went wrong</c>
    ///     </para>
    /// </summary>
    /// <param name="traceId">The value passed to the base type constructor.</param>
    /// <returns>A new instance of <see cref="MyError"/>.</returns>
    public static MyError From(global::System.Guid traceId)
    {
        var message = "Something went wrong";

        return new MyError(traceId)
        {
            Message = message,
        };
    }
}
