// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

internal partial record InternalError
{
    public String Message { get; private init; } = default!;

    private InternalError() { }


    /// <summary>
    ///     Creates a new <see cref="InternalError"/> with the message template:
    ///     <para>
    ///         <c>Internal error</c>
    ///     </para>
    /// </summary>
    /// <returns>A new instance of <see cref="InternalError"/>.</returns>
    public static InternalError From()
    {
        var message = "Internal error";

        return new InternalError()
        {
            Message = message,
        };
    }
}
