// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

public partial record AuthError
{

    public String UserId { get; private init; } = default!;

    private AuthError(string message, global::System.Guid traceId) : base(message, traceId) { }


    /// <summary>
    ///     Creates a new <see cref="AuthError"/> with the message template:
    ///     <para>
    ///         <c>Auth failed for '{UserId:String}'</c>
    ///     </para>
    /// </summary>
    /// <param name="traceId">The value passed to the base type constructor.</param>
    /// <param name="userId">The value for the <c>{UserId}</c> placeholder.</param>
    /// <returns>A new instance of <see cref="AuthError"/>.</returns>
    public static AuthError FromUserId(global::System.Guid traceId, String userId)
    {
        var message = String.Concat(
            "Auth failed for '",
            userId,
            "'"
        );

        return new AuthError(message, traceId)
        {
            UserId = userId,
        };
    }
}
