// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

public partial record EmptyError
{
    public String Message { get; private init; } = default!;

    private EmptyError() { }


    /// <summary>
    ///     Creates a new <see cref="EmptyError"/> with the message template:
    ///     <para>
    ///         <c></c>
    ///     </para>
    /// </summary>
    /// <returns>A new instance of <see cref="EmptyError"/>.</returns>
    public static EmptyError From()
    {
        var message = "";

        return new EmptyError()
        {
            Message = message,
        };
    }
}
