// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

public partial record UserNotFoundError
{
    public String Message { get; private init; } = default!;

    public String Name { get; private init; } = default!;

    public Int32 Id { get; private init; } = default!;

    private UserNotFoundError() { }


    /// <summary>
    ///     Creates a new <see cref="UserNotFoundError"/> with the message template:
    ///     <para>
    ///         <c>User '{Name:String}' was not found</c>
    ///     </para>
    /// </summary>
    /// <param name="name">The value for the <c>{Name}</c> placeholder.</param>
    /// <returns>A new instance of <see cref="UserNotFoundError"/>.</returns>
    public static UserNotFoundError FromName(String name)
    {
        var message = String.Concat(
            "User '",
            name,
            "' was not found"
        );

        return new UserNotFoundError()
        {
            Message = message,
            Name = name,
        };
    }

    /// <summary>
    ///     Creates a new <see cref="UserNotFoundError"/> with the message template:
    ///     <para>
    ///         <c>User with ID {Id:Int32} was not found</c>
    ///     </para>
    /// </summary>
    /// <param name="id">The value for the <c>{Id}</c> placeholder.</param>
    /// <returns>A new instance of <see cref="UserNotFoundError"/>.</returns>
    public static UserNotFoundError FromId(Int32 id)
    {
        var message = String.Concat(
            "User with ID ",
            id,
            " was not found"
        );

        return new UserNotFoundError()
        {
            Message = message,
            Id = id,
        };
    }
}
