// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

public partial record ConnectionError
{
    public String Message { get; private init; } = default!;

    public String Host { get; private init; } = default!;

    public Int32 TimeoutMs { get; private init; } = default!;

    public Int32 Port { get; private init; } = default!;

    private ConnectionError() { }


    /// <summary>
    ///     Creates a new <see cref="ConnectionError"/> with the message template:
    ///     <para>
    ///         <c>Connection to '{Host:String}' timed out after {TimeoutMs:Int32}ms</c>
    ///     </para>
    /// </summary>
    /// <param name="host">The value for the <c>{Host}</c> placeholder.</param>
    /// <param name="timeoutMs">The value for the <c>{TimeoutMs}</c> placeholder.</param>
    /// <returns>A new instance of <see cref="ConnectionError"/>.</returns>
    public static ConnectionError FromHostAndTimeoutMs(String host, Int32 timeoutMs)
    {
        var message = String.Concat(
            "Connection to '",
            host,
            "' timed out after ",
            timeoutMs,
            "ms"
        );

        return new ConnectionError()
        {
            Message = message,
            Host = host,
            TimeoutMs = timeoutMs,
        };
    }

    /// <summary>
    ///     Creates a new <see cref="ConnectionError"/> with the message template:
    ///     <para>
    ///         <c>Connection to '{Host:String}' was refused on port {Port:Int32}</c>
    ///     </para>
    /// </summary>
    /// <param name="host">The value for the <c>{Host}</c> placeholder.</param>
    /// <param name="port">The value for the <c>{Port}</c> placeholder.</param>
    /// <returns>A new instance of <see cref="ConnectionError"/>.</returns>
    public static ConnectionError FromHostAndPort(String host, Int32 port)
    {
        var message = String.Concat(
            "Connection to '",
            host,
            "' was refused on port ",
            port
        );

        return new ConnectionError()
        {
            Message = message,
            Host = host,
            Port = port,
        };
    }
}
