// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

public partial record HttpError
{
    public String Message { get; private init; } = default!;

    public String Method { get; private init; } = default!;

    public String Path { get; private init; } = default!;

    public Int32 StatusCode { get; private init; } = default!;

    private HttpError() { }


    /// <summary>
    ///     Creates a new <see cref="HttpError"/> with the message template:
    ///     <para>
    ///         <c>{Method:String} {Path:String} returned {StatusCode:Int32}</c>
    ///     </para>
    /// </summary>
    /// <param name="method">The value for the <c>{Method}</c> placeholder.</param>
    /// <param name="path">The value for the <c>{Path}</c> placeholder.</param>
    /// <param name="statusCode">The value for the <c>{StatusCode}</c> placeholder.</param>
    /// <returns>A new instance of <see cref="HttpError"/>.</returns>
    public static HttpError FromMethodPathAndStatusCode(String method, String path, Int32 statusCode)
    {
        var message = String.Concat(
            method,
            " ",
            path,
            " returned ",
            statusCode
        );

        return new HttpError()
        {
            Message = message,
            Method = method,
            Path = path,
            StatusCode = statusCode,
        };
    }
}
