// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

public partial record DuplicateArgError
{
    public String Message { get; private init; } = default!;

    public String Value { get; private init; } = default!;

    private DuplicateArgError() { }


    /// <summary>
    ///     Creates a new <see cref="DuplicateArgError"/> with the message template:
    ///     <para>
    ///         <c>Expected {Value:String} but got {Value:String} again</c>
    ///     </para>
    /// </summary>
    /// <param name="value">The value for the <c>{Value}</c> placeholder.</param>
    /// <returns>A new instance of <see cref="DuplicateArgError"/>.</returns>
    public static DuplicateArgError FromValue(String value)
    {
        var message = String.Concat(
            "Expected ",
            value,
            " but got ",
            value,
            " again"
        );

        return new DuplicateArgError()
        {
            Message = message,
            Value = value,
        };
    }
}
