// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

public partial record struct GreetingError
{
    public String Message { get; private init; } = default!;

    public String Name { get; private init; } = default!;

    public GreetingError() { }


    /// <summary>
    ///     Creates a new <see cref="GreetingError"/> with the message template:
    ///     <para>
    ///         <c>Hello {Name:String}!</c>
    ///     </para>
    /// </summary>
    /// <param name="name">The value for the <c>{Name}</c> placeholder.</param>
    /// <returns>A new instance of <see cref="GreetingError"/>.</returns>
    public static GreetingError FromName(String name)
    {
        var message = String.Concat(
            "Hello ",
            name,
            "!"
        );

        return new GreetingError()
        {
            Message = message,
            Name = name,
        };
    }
}
