// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

public partial record WhitespaceError
{
    public String Message { get; private init; } = default!;

    private WhitespaceError() { }


    /// <summary>
    ///     Creates a new <see cref="WhitespaceError"/> with the message template:
    ///     <para>
    ///         <c>   </c>
    ///     </para>
    /// </summary>
    /// <returns>A new instance of <see cref="WhitespaceError"/>.</returns>
    public static WhitespaceError From()
    {
        var message = "   ";

        return new WhitespaceError()
        {
            Message = message,
        };
    }
}
