// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

public partial record InvalidAnswer : global::TestNamespace.Error
{

    public Int32 Answer { get; private init; } = default!;

    private InvalidAnswer(string message, global::System.Guid userId) : base(message, userId) { }


    /// <summary>
    ///     Creates a new <see cref="InvalidAnswer"/> with the message template:
    ///     <para>
    ///         <c>The answer {Answer:Int32} was incorrect.</c>
    ///     </para>
    /// </summary>
    /// <param name="userId">The value passed to the base type constructor.</param>
    /// <param name="answer">The value for the <c>{Answer}</c> placeholder.</param>
    /// <returns>A new instance of <see cref="InvalidAnswer"/>.</returns>
    public static InvalidAnswer FromAnswer(global::System.Guid userId, Int32 answer)
    {
        var message = String.Concat(
            "The answer ",
            answer,
            " was incorrect."
        );

        return new InvalidAnswer(message, userId)
        {
            Answer = answer,
        };
    }
}
