// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

public partial record ComparisonError
{
    public String Message { get; private init; } = default!;

    public Int32 X { get; private init; } = default!;

    public Int32 Y { get; private init; } = default!;

    private ComparisonError() { }


    /// <summary>
    ///     Creates a new <see cref="ComparisonError"/> with the message template:
    ///     <para>
    ///         <c>Expected {X:Int32} &lt; {Y:Int32} &amp;&amp; {X:Int32} &gt; 0</c>
    ///     </para>
    /// </summary>
    /// <param name="x">The value for the <c>{X}</c> placeholder.</param>
    /// <param name="y">The value for the <c>{Y}</c> placeholder.</param>
    /// <returns>A new instance of <see cref="ComparisonError"/>.</returns>
    public static ComparisonError FromXAndY(Int32 x, Int32 y)
    {
        var message = String.Concat(
            "Expected ",
            x,
            " < ",
            y,
            " && ",
            x,
            " > 0"
        );

        return new ComparisonError()
        {
            Message = message,
            X = x,
            Y = y,
        };
    }
}
