// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

public partial record UserNotFoundError
{
    public String Message { get; private init; } = default!;

    public Object? Name { get; private init; } = default!;

    private UserNotFoundError() { }


    /// <summary>
    ///     Creates a new <see cref="UserNotFoundError"/> with the message template:
    ///     <para>
    ///         <c>User {Name} was not found</c>
    ///     </para>
    /// </summary>
    /// <param name="name">The value for the <c>{Name}</c> placeholder.</param>
    /// <returns>A new instance of <see cref="UserNotFoundError"/>.</returns>
    public static UserNotFoundError FromName(Object? name)
    {
        var message = String.Concat(
            "User ",
            name,
            " was not found"
        );

        return new UserNotFoundError()
        {
            Message = message,
            Name = name,
        };
    }
}
