// <auto-generated/>
#nullable enable

using System;

namespace TestNamespace;

public partial record MyError
{

    private MyError(string message) : base(message) { }


    /// <summary>
    ///     Creates a new <see cref="MyError"/> with the message template:
    ///     <para>
    ///         <c>Something failed</c>
    ///     </para>
    /// </summary>
    /// <returns>A new instance of <see cref="MyError"/>.</returns>
    public static MyError From()
    {
        var message = "Something failed";

        return new MyError(message)
        {
        };
    }
}
