// <auto-generated/>
#nullable enable

using System;

namespace My.Custom.Namespace;

public partial record CustomError
{
    public String Message { get; private init; } = default!;

    private CustomError() { }


    /// <summary>
    ///     Creates a new <see cref="CustomError"/> with the message template:
    ///     <para>
    ///         <c>Something went wrong</c>
    ///     </para>
    /// </summary>
    /// <returns>A new instance of <see cref="CustomError"/>.</returns>
    public static CustomError From()
    {
        var message = "Something went wrong";

        return new CustomError()
        {
            Message = message,
        };
    }
}
