using System;
using System.Linq;
using Base16.ErrGen.Extensions;
using Base16.ErrGen.Utils.Code;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Base16.ErrGen.ErrorTypes;

[Generator]
public sealed class ErrorTypesGenerator : IIncrementalGenerator
{
    private const String ErrorAttributeName = "Base16.ErrGen.ErrorAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(
                "Base16.ErrGen.ErrorAttribute.g.cs",
                """
                // <auto-generated/>
                #nullable enable

                namespace Base16.ErrGen;

                /// <summary>
                ///     Marks a partial record struct as an error type and defines a message template.
                ///     Can be applied multiple times to generate multiple factory methods.
                /// </summary>[System.AttributeUsage(System.AttributeTargets.Struct, AllowMultiple = true)]
                #pragma warning disable CS9113 // Parameter is unread.
                [System.AttributeUsage(System.AttributeTargets.Struct, AllowMultiple = true)]
                public sealed class ErrorAttribute : System.Attribute
                {
                    /// <summary>
                    ///     The message template. Use {Name} or {Name:Type} placeholders.
                    /// </summary>
                    public System.String Template { get; }

                    public ErrorAttribute(System.String template)
                    {
                        Template = template;
                    }
                }
                #pragma warning restore CS9113 // Parameter is unread.
                """
            );
        });

        var errorTypes = context.SyntaxProvider.ForAttributeWithMetadataName(
            ErrorAttributeName,
            predicate: (node, _) => node is RecordDeclarationSyntax,
            transform: (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol
        );

        context.RegisterSourceOutput(errorTypes, GenerateExtensionsForSucessResults);
    }

    private void GenerateExtensionsForSucessResults(
        SourceProductionContext context,
        INamedTypeSymbol errorType
    )
    {
#pragma warning disable IDE0072 // Populate switch
        var accessability = errorType.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            _ => throw new NotSupportedException(),
        };
#pragma warning restore IDE0072

        var cb = CSharpCodeBuilder.NewFile();

        var recordType = errorType.TypeKind == TypeKind.Struct ? "record struct" : "record";

        cb.AppendLines(
            $"""
            using System;

            namespace {errorType.ContainingNamespace.ToDisplayString()};

            {accessability} partial {recordType} {errorType.Name}
            """
        );

        var errorTemplates = errorType
            .GetAttributes()
            .Where(x => x.AttributeClass!.ToDisplayString() == ErrorAttributeName)
            .Select(x => x.ConstructorArguments[0].Value)
            .OfType<String>()
            .Select(StringTemplate.Parse)
            .ToList();

        using (cb.PushScope())
        {
            cb.AppendLine("public String Message { get; private set; } = default!;");
            cb.AppendLine();
            var templates = errorTemplates
                .SelectMany(x => x.Parts)
                .OfType<StringTemplateArgumentPart>()
                .DistinctBy(x => x.Name)
                .ToList();
            foreach (var template in templates)
            {
                cb.AppendLine(
                    $"public {template.Type ?? "Object?"} {template.Name} {{ get; private set; }} = default!;"
                );
                cb.AppendLine();
            }

            cb.AppendLine($"public {errorType.Name}() {{ }}");
            cb.AppendLine();

            cb.AppendLine($"public {errorType.Name}(String message)");
            using (cb.PushScope())
                cb.AppendLine("Message = message;");

            foreach (var template in errorTemplates)
            {
                var arguments = template
                    .Parts.OfType<StringTemplateArgumentPart>()
                    .DistinctBy(x => x.Name)
                    .ToList();

                var namePart = String.Join("And", arguments.Select(x => x.Name));
                var args = String.Join(
                    ", ",
                    arguments.Select(x => $"{x.Type ?? "Object?"} {x.Name.ToCamelCase()}")
                );

                cb.AppendLine();
                cb.AppendLine($"public static {errorType.Name} From{namePart}({args})");
                using (cb.PushScope())
                {
                    cb.AppendLine($"return new {errorType.Name}");
                    using (cb.PushScopeExpression())
                    {
                        cb.AppendLine($"Message = String.Concat(");
                        foreach (var templatePart in template.Parts)
                        {
                            var isLast = templatePart == template.Parts.Last();
                            var str = templatePart switch
                            {
                                StringTemplateLiteralPart part => $"\"{part.Value}\"",
                                StringTemplateArgumentPart part => $"{part.Name.ToCamelCase()}",
                                _ => throw new NotSupportedException(
                                    $"Template part of type '{templatePart.GetType().Name}' is not supported."
                                ),
                            };

                            cb.AppendLineIndented($"{str}{(isLast ? "" : ",")}");
                        }
                        cb.AppendLine($"),");
                        foreach (var argument in arguments)
                            cb.AppendLine($"{argument.Name} = {argument.Name.ToCamelCase()},");
                    }
                }
            }
        }

        context.AddSource($"{errorType.ToDisplayString()}.g.cs", cb.ToString());
    }
}
