using System;
using System.Linq;
using Base16.ErrGen.Extensions;
using Base16.ErrGen.Utils.Code;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Base16.ErrGen.ErrorTypes;

[Generator]
public sealed class ErrorTypesGenerator : IIncrementalGenerator
{
    private const String ErrorAttributeName = "Base16.ErrGen.ErrorAttribute";
    private const String ErrorBaseTypeAttributeName = "Base16.ErrGen.ErrorBaseTypeAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(
                "Base16.ErrGen.IsExternalInit.g.cs",
                """
                // <auto-generated/>
                #if !NET5_0_OR_GREATER
                namespace System.Runtime.CompilerServices
                {
                    internal static class IsExternalInit { }
                }
                #endif
                """
            );

            ctx.AddSource(
                "Base16.ErrGen.ErrorAttribute.g.cs",
                """
                // <auto-generated/>
                #nullable enable

                namespace Base16.ErrGen;

                /// <summary>
                ///     Marks a partial record struct as an error type and defines a message template.
                ///     Can be applied multiple times to generate multiple factory methods.
                /// </summary>
                #pragma warning disable CS9113 // Parameter is unread.
                [System.AttributeUsage(System.AttributeTargets.Struct | System.AttributeTargets.Class, AllowMultiple = true)]
                public sealed class ErrorAttribute : System.Attribute
                {
                    /// <summary>
                    ///     The message template. Use {Name} or {Name:Type} placeholders.
                    /// </summary>
                    public System.String Template { get; }

                    public ErrorAttribute(System.String template)
                    {
                        Template = template;
                    }
                }
                #pragma warning restore CS9113 // Parameter is unread.
                """
            );

            ctx.AddSource(
                "Base16.ErrGen.ErrorBaseTypeAttribute.g.cs",
                """
                // <auto-generated/>
                #nullable enable

                namespace Base16.ErrGen;

                /// <summary>
                ///     Configures a base type (interface or class) that all generated error types inherit from.
                /// </summary>
                #pragma warning disable CS9113 // Parameter is unread.
                [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple = false)]
                public sealed class ErrorBaseTypeAttribute : System.Attribute
                {
                    /// <summary>
                    ///     The base type to inherit from.
                    /// </summary>
                    public System.Type Type { get; }

                    public ErrorBaseTypeAttribute(System.Type type)
                    {
                        Type = type;
                    }
                }
                #pragma warning restore CS9113 // Parameter is unread.
                """
            );
        });

        var baseTypeInfo = context.CompilationProvider.Select(
            static (compilation, ct) =>
            {
                var assemblyAttributes = compilation.Assembly.GetAttributes();
                var attr = assemblyAttributes.FirstOrDefault(a =>
                    a.AttributeClass?.ToDisplayString() == ErrorBaseTypeAttributeName
                );

                if (attr is null)
                    return (Info: (ErrorBaseTypeInfo?)null, Diagnostic: (Diagnostic?)null);

                if (
                    attr.ConstructorArguments.Length == 0
                    || attr.ConstructorArguments[0].Value is not INamedTypeSymbol typeSymbol
                )
                {
                    return (
                        Info: null,
                        Diagnostic: Diagnostic.Create(
                            ErrorDiagnostics.InvalidBaseType,
                            attr.ApplicationSyntaxReference?.GetSyntax(ct).GetLocation(),
                            attr.ConstructorArguments.Length > 0
                                ? attr.ConstructorArguments[0].Value?.ToString() ?? "unknown"
                                : "unknown"
                        )
                    );
                }

                if (
                    typeSymbol.TypeKind != TypeKind.Interface
                    && typeSymbol.TypeKind != TypeKind.Class
                )
                {
                    return (
                        Info: null,
                        Diagnostic: Diagnostic.Create(
                            ErrorDiagnostics.InvalidBaseType,
                            attr.ApplicationSyntaxReference?.GetSyntax(ct).GetLocation(),
                            typeSymbol.ToDisplayString()
                        )
                    );
                }

                if (typeSymbol.IsGenericType)
                {
                    return (
                        Info: null,
                        Diagnostic: Diagnostic.Create(
                            ErrorDiagnostics.GenericBaseType,
                            attr.ApplicationSyntaxReference?.GetSyntax(ct).GetLocation(),
                            typeSymbol.ToDisplayString()
                        )
                    );
                }

                var messageProperty = FindPropertyInHierarchy(typeSymbol, "Message");

                if (
                    messageProperty is not null
                    && messageProperty.Type.SpecialType != SpecialType.System_String
                )
                {
                    return (
                        Info: null,
                        Diagnostic: Diagnostic.Create(
                            ErrorDiagnostics.MessagePropertyNotString,
                            attr.ApplicationSyntaxReference?.GetSyntax(ct).GetLocation(),
                            typeSymbol.ToDisplayString()
                        )
                    );
                }

                return (Info: (ErrorBaseTypeInfo?)BuildBaseTypeInfo(typeSymbol), Diagnostic: null);
            }
        );

        var errorTypes = context.SyntaxProvider.ForAttributeWithMetadataName(
            ErrorAttributeName,
            predicate: (node, _) => node is RecordDeclarationSyntax,
            transform: static (ctx, _) =>
            {
                var symbol = (INamedTypeSymbol)ctx.TargetSymbol;

                ErrorBaseTypeInfo? explicitBase = null;
                if (
                    symbol.BaseType is
                    {
                        SpecialType: not SpecialType.System_Object
                            and not SpecialType.System_ValueType,
                    } baseType
                )
                {
                    explicitBase = BuildBaseTypeInfo(baseType);
                }

                return (Symbol: symbol, ExplicitBase: explicitBase);
            }
        );

        var combined = errorTypes.Combine(baseTypeInfo);

        context.RegisterSourceOutput(
            baseTypeInfo,
            static (context, result) =>
            {
                if (result.Diagnostic is not null)
                    context.ReportDiagnostic(result.Diagnostic);
            }
        );

        context.RegisterSourceOutput(
            combined,
            (context, pair) =>
            {
                var (errorInfo, assemblyBase) = pair;
                var hasExplicitBase = errorInfo.ExplicitBase is not null;
                var effectiveBase = errorInfo.ExplicitBase ?? assemblyBase.Info;
                GenerateExtensionsForSuccessResults(
                    context,
                    errorInfo.Symbol,
                    effectiveBase,
                    hasExplicitBase
                );
            }
        );
    }

    private void GenerateExtensionsForSuccessResults(
        SourceProductionContext context,
        INamedTypeSymbol errorType,
        ErrorBaseTypeInfo? baseTypeInfo,
        Boolean hasExplicitBase
    )
    {
#pragma warning disable IDE0072 // Populate switch
        var accessability = errorType.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            _ => throw new NotSupportedException(),
        };
#pragma warning restore IDE0072

        var cb = CSharpCodeBuilder.NewFile();

        var isStruct = errorType.TypeKind == TypeKind.Struct;
        var recordType = isStruct ? "record struct" : "record";

        var baseTypeSuffix = "";
        if (baseTypeInfo is not null && !hasExplicitBase)
        {
            if (!baseTypeInfo.IsInterface && isStruct)
            {
                context.ReportDiagnostic(
                    Diagnostic.Create(
                        ErrorDiagnostics.StructCannotInheritClass,
                        errorType.Locations.FirstOrDefault(),
                        errorType.Name,
                        baseTypeInfo.FullyQualifiedName
                    )
                );
                return;
            }
            baseTypeSuffix = $" : {baseTypeInfo.FullyQualifiedName}";
        }

        cb.AppendLines(
            $"""
            using System;

            namespace {errorType.ContainingNamespace.ToDisplayString()};

            {accessability} partial {recordType} {errorType.Name}{baseTypeSuffix}
            """
        );

        var errorTemplates = errorType
            .GetAttributes()
            .Where(x => x.AttributeClass!.ToDisplayString() == ErrorAttributeName)
            .Select(x => x.ConstructorArguments[0].Value)
            .OfType<String>()
            .Select(StringTemplate.Parse)
            .ToList();

        using (cb.PushScope())
        {
            var skipMessage = baseTypeInfo?.HasMessageProperty == true;
            if (!skipMessage)
                cb.AppendLine("public String Message { get; private set; } = default!;");
            cb.AppendLine();
            var templates = errorTemplates
                .SelectMany(x => x.Parts)
                .OfType<StringTemplateArgumentPart>()
                .DistinctBy(x => x.Name)
                .ToList();
            foreach (var template in templates)
            {
                cb.AppendLine(
                    $"public {template.Type ?? "Object?"} {template.Name} {{ get; private set; }} = default!;"
                );
                cb.AppendLine();
            }

            var ctorAccess = isStruct ? "public" : "private";
            var ctorParams = baseTypeInfo?.BaseCtorParamDeclarations is { Length: > 0 } paramDecl
                ? paramDecl
                : "";
            var baseCtorCall = baseTypeInfo?.BaseCtorCallArgs is { Length: > 0 } baseCallArgs
                ? $" : base({baseCallArgs})"
                : "";
            cb.AppendLine($"{ctorAccess} {errorType.Name}({ctorParams}){baseCtorCall} {{ }}");
            cb.AppendLine();

            foreach (var template in errorTemplates)
            {
                var arguments = template
                    .Parts.OfType<StringTemplateArgumentPart>()
                    .DistinctBy(x => x.Name)
                    .ToList();

                var namePart = arguments.Count switch
                {
                    0 => String.Empty,
                    1 => arguments[0].Name,
                    _ => String.Concat([
                        .. arguments.Select(x => x.Name).Take(arguments.Count - 1),
                        "And",
                        arguments.Last().Name,
                    ]),
                };

                var templateArgs = arguments.Select(x =>
                    $"{x.Type ?? "Object?"} {x.Name.ToCamelCase()}"
                );
                var allArgs = baseTypeInfo?.BaseFactoryParamDeclarations
                    is { Length: > 0 } factoryParams
                    ? String.Join(", ", new[] { factoryParams }.Concat(templateArgs))
                    : String.Join(", ", templateArgs);

                cb.AppendLine();
                cb.AppendLine($"public static {errorType.Name} From{namePart}({allArgs})");
                using (cb.PushScope())
                {
                    cb.AppendLine($"var message = String.Concat(");
                    foreach (var templatePart in template.Parts)
                    {
                        var isLast = templatePart == template.Parts.Last();
                        var str = templatePart switch
                        {
                            StringTemplateLiteralPart part => $"\"{part.Value}\"",
                            StringTemplateArgumentPart part => $"{part.Name.ToCamelCase()}",
                            _ => throw new NotSupportedException(
                                $"Template part of type '{templatePart.GetType().Name}' is not supported."
                            ),
                        };

                        cb.AppendLineIndented($"{str}{(isLast ? "" : ",")}");
                    }
                    cb.AppendLine(");");
                    cb.AppendLine();

                    var ctorCallArgs = baseTypeInfo?.BaseCtorCallArgs is { Length: > 0 } callArgs
                        ? callArgs
                        : "";
                    cb.AppendLine($"return new {errorType.Name}({ctorCallArgs})");
                    using (cb.PushScopeExpression())
                    {
                        if (String.IsNullOrEmpty(ctorCallArgs))
                            cb.AppendLine($"Message = message,");
                        foreach (var argument in arguments)
                            cb.AppendLine($"{argument.Name} = {argument.Name.ToCamelCase()},");
                    }
                }
            }
        }

        context.AddSource($"{errorType.ToDisplayString()}.g.cs", cb.ToString());
    }

    private static IPropertySymbol? FindPropertyInHierarchy(
        INamedTypeSymbol typeSymbol,
        String name
    )
    {
        var current = typeSymbol;
        while (current is not null)
        {
            var prop = current
                .GetMembers()
                .OfType<IPropertySymbol>()
                .FirstOrDefault(p => p.Name == name);
            if (prop is not null)
                return prop;
            current = current.BaseType;
        }
        return null;
    }

    private static ErrorBaseTypeInfo BuildBaseTypeInfo(INamedTypeSymbol typeSymbol)
    {
        var messageProperty = FindPropertyInHierarchy(typeSymbol, "Message");

        var primaryCtor = typeSymbol
            .InstanceConstructors.Where(c =>
                !(
                    c.Parameters.Length == 1
                    && SymbolEqualityComparer.Default.Equals(c.Parameters[0].Type, typeSymbol)
                )
            )
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault();

        var ctorParams =
            primaryCtor?.Parameters
            ?? System.Collections.Immutable.ImmutableArray<IParameterSymbol>.Empty;

        var baseCtorParamDeclarations = String.Join(
            ", ",
            ctorParams.Select(p =>
                $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {p.Name.ToCamelCase()}"
            )
        );

        var baseCtorCallArgs = String.Join(", ", ctorParams.Select(p => p.Name.ToCamelCase()));

        var baseFactoryParamDeclarations = String.Join(
            ", ",
            ctorParams
                .Where(p =>
                    !(p.Name == "Message" && p.Type.SpecialType == SpecialType.System_String)
                )
                .Select(p =>
                    $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {p.Name.ToCamelCase()}"
                )
        );

        return new ErrorBaseTypeInfo(
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeSymbol.TypeKind == TypeKind.Interface,
            messageProperty is not null,
            baseCtorParamDeclarations,
            baseCtorCallArgs,
            baseFactoryParamDeclarations
        );
    }
}
