using System;
using System.Linq;
using Base16.ErrGen.Extensions;
using Base16.ErrGen.Utils.Code;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Base16.ErrGen.ErrorTypes;

[Generator]
public sealed class ErrorTypesGenerator : IIncrementalGenerator
{
    private const String ErrorAttributeName = "Base16.ErrGen.ErrorAttribute";
    private const String ErrorBaseTypeAttributeName = "Base16.ErrGen.ErrorBaseTypeAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(
                "Base16.ErrGen.IsExternalInit.g.cs",
                """
                // <auto-generated/>
                #if !NET5_0_OR_GREATER
                namespace System.Runtime.CompilerServices
                {
                    internal static class IsExternalInit { }
                }
                #endif
                """
            );

            ctx.AddSource(
                "Base16.ErrGen.ErrorAttribute.g.cs",
                """
                // <auto-generated/>
                #nullable enable

                namespace Base16.ErrGen;

                /// <summary>
                ///     Marks a partial record struct as an error type and defines a message template.
                ///     Can be applied multiple times to generate multiple factory methods.
                /// </summary>
                #pragma warning disable CS9113 // Parameter is unread.
                [System.AttributeUsage(System.AttributeTargets.Struct | System.AttributeTargets.Class, AllowMultiple = true)]
                public sealed class ErrorAttribute : System.Attribute
                {
                    /// <summary>
                    ///     The message template. Use {Name} or {Name:Type} placeholders.
                    /// </summary>
                    public System.String Template { get; }

                    public ErrorAttribute(System.String template)
                    {
                        Template = template;
                    }
                }
                #pragma warning restore CS9113 // Parameter is unread.
                """
            );

            ctx.AddSource(
                "Base16.ErrGen.ErrorBaseTypeAttribute.g.cs",
                """
                // <auto-generated/>
                #nullable enable

                namespace Base16.ErrGen;

                /// <summary>
                ///     Configures a base type (interface or class) that all generated error types inherit from.
                /// </summary>
                #pragma warning disable CS9113 // Parameter is unread.
                [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple = false)]
                public sealed class ErrorBaseTypeAttribute : System.Attribute
                {
                    /// <summary>
                    ///     The base type to inherit from.
                    /// </summary>
                    public System.Type Type { get; }

                    public ErrorBaseTypeAttribute(System.Type type)
                    {
                        Type = type;
                    }
                }
                #pragma warning restore CS9113 // Parameter is unread.
                """
            );
        });

        var baseTypeInfo = context.CompilationProvider.Select(
            static (compilation, ct) =>
            {
                var assemblyAttributes = compilation.Assembly.GetAttributes();
                var attr = assemblyAttributes.FirstOrDefault(a =>
                    a.AttributeClass?.ToDisplayString() == ErrorBaseTypeAttributeName
                );

                if (attr is null)
                    return (Info: (ErrorBaseTypeInfo?)null, Diagnostic: (Diagnostic?)null);

                if (
                    attr.ConstructorArguments.Length == 0
                    || attr.ConstructorArguments[0].Value is not INamedTypeSymbol typeSymbol
                )
                {
                    return (
                        Info: null,
                        Diagnostic: Diagnostic.Create(
                            ErrorDiagnostics.InvalidBaseType,
                            attr.ApplicationSyntaxReference?.GetSyntax(ct).GetLocation(),
                            attr.ConstructorArguments.Length > 0
                                ? attr.ConstructorArguments[0].Value?.ToString() ?? "unknown"
                                : "unknown"
                        )
                    );
                }

                if (
                    typeSymbol.TypeKind != TypeKind.Interface
                    && typeSymbol.TypeKind != TypeKind.Class
                )
                {
                    return (
                        Info: null,
                        Diagnostic: Diagnostic.Create(
                            ErrorDiagnostics.InvalidBaseType,
                            attr.ApplicationSyntaxReference?.GetSyntax(ct).GetLocation(),
                            typeSymbol.ToDisplayString()
                        )
                    );
                }

                if (typeSymbol.IsAbstract && typeSymbol.TypeKind == TypeKind.Class)
                {
                    return (
                        Info: null,
                        Diagnostic: Diagnostic.Create(
                            ErrorDiagnostics.AbstractBaseType,
                            attr.ApplicationSyntaxReference?.GetSyntax(ct).GetLocation(),
                            typeSymbol.ToDisplayString()
                        )
                    );
                }

                if (typeSymbol.IsGenericType)
                {
                    return (
                        Info: null,
                        Diagnostic: Diagnostic.Create(
                            ErrorDiagnostics.GenericBaseType,
                            attr.ApplicationSyntaxReference?.GetSyntax(ct).GetLocation(),
                            typeSymbol.ToDisplayString()
                        )
                    );
                }

                var messageProperty = typeSymbol
                    .GetMembers()
                    .OfType<IPropertySymbol>()
                    .FirstOrDefault(p => p.Name == "Message");

                if (
                    messageProperty is not null
                    && messageProperty.Type.SpecialType != SpecialType.System_String
                )
                {
                    return (
                        Info: null,
                        Diagnostic: Diagnostic.Create(
                            ErrorDiagnostics.MessagePropertyNotString,
                            attr.ApplicationSyntaxReference?.GetSyntax(ct).GetLocation(),
                            typeSymbol.ToDisplayString()
                        )
                    );
                }

                return (
                    Info: (ErrorBaseTypeInfo?)
                        new ErrorBaseTypeInfo(
                            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                            typeSymbol.TypeKind == TypeKind.Interface,
                            messageProperty is not null
                        ),
                    Diagnostic: null
                );
            }
        );

        var errorTypes = context.SyntaxProvider.ForAttributeWithMetadataName(
            ErrorAttributeName,
            predicate: (node, _) => node is RecordDeclarationSyntax,
            transform: (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol
        );

        var combined = errorTypes.Combine(baseTypeInfo);

        context.RegisterSourceOutput(
            baseTypeInfo,
            static (context, result) =>
            {
                if (result.Diagnostic is not null)
                    context.ReportDiagnostic(result.Diagnostic);
            }
        );

        context.RegisterSourceOutput(
            combined,
            (context, pair) =>
            {
                var (errorType, baseType) = pair;
                GenerateExtensionsForSucessResults(context, errorType, baseType.Info);
            }
        );
    }

    private void GenerateExtensionsForSucessResults(
        SourceProductionContext context,
        INamedTypeSymbol errorType,
        ErrorBaseTypeInfo? baseTypeInfo
    )
    {
#pragma warning disable IDE0072 // Populate switch
        var accessability = errorType.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            _ => throw new NotSupportedException(),
        };
#pragma warning restore IDE0072

        var cb = CSharpCodeBuilder.NewFile();

        var isStruct = errorType.TypeKind == TypeKind.Struct;
        var recordType = isStruct ? "record struct" : "record";

        var baseTypeSuffix = "";
        if (baseTypeInfo is not null)
        {
            if (!baseTypeInfo.IsInterface && isStruct)
            {
                context.ReportDiagnostic(
                    Diagnostic.Create(
                        ErrorDiagnostics.StructCannotInheritClass,
                        errorType.Locations.FirstOrDefault(),
                        errorType.Name,
                        baseTypeInfo.FullyQualifiedName
                    )
                );
                return;
            }
            baseTypeSuffix = $" : {baseTypeInfo.FullyQualifiedName}";
        }

        cb.AppendLines(
            $"""
            using System;

            namespace {errorType.ContainingNamespace.ToDisplayString()};

            {accessability} partial {recordType} {errorType.Name}{baseTypeSuffix}
            """
        );

        var errorTemplates = errorType
            .GetAttributes()
            .Where(x => x.AttributeClass!.ToDisplayString() == ErrorAttributeName)
            .Select(x => x.ConstructorArguments[0].Value)
            .OfType<String>()
            .Select(StringTemplate.Parse)
            .ToList();

        using (cb.PushScope())
        {
            var skipMessage = baseTypeInfo?.HasMessageProperty == true;
            if (!skipMessage)
                cb.AppendLine("public String Message { get; private set; } = default!;");
            cb.AppendLine();
            var templates = errorTemplates
                .SelectMany(x => x.Parts)
                .OfType<StringTemplateArgumentPart>()
                .DistinctBy(x => x.Name)
                .ToList();
            foreach (var template in templates)
            {
                cb.AppendLine(
                    $"public {template.Type ?? "Object?"} {template.Name} {{ get; private set; }} = default!;"
                );
                cb.AppendLine();
            }

            cb.AppendLine($"{(isStruct ? "public" : "private")} {errorType.Name}() {{ }}");
            cb.AppendLine();

            foreach (var template in errorTemplates)
            {
                var arguments = template
                    .Parts.OfType<StringTemplateArgumentPart>()
                    .DistinctBy(x => x.Name)
                    .ToList();

                var namePart = arguments.Count switch
                {
                    0 => String.Empty,
                    1 => arguments[0].Name,
                    _ => String.Concat([
                        .. arguments.Select(x => x.Name).Take(arguments.Count - 1),
                        "And",
                        arguments.Last().Name,
                    ]),
                };

                var args = String.Join(
                    ", ",
                    arguments.Select(x => $"{x.Type ?? "Object?"} {x.Name.ToCamelCase()}")
                );

                cb.AppendLine();
                cb.AppendLine($"public static {errorType.Name} From{namePart}({args})");
                using (cb.PushScope())
                {
                    cb.AppendLine($"return new {errorType.Name}");
                    using (cb.PushScopeExpression())
                    {
                        cb.AppendLine($"Message = String.Concat(");
                        foreach (var templatePart in template.Parts)
                        {
                            var isLast = templatePart == template.Parts.Last();
                            var str = templatePart switch
                            {
                                StringTemplateLiteralPart part => $"\"{part.Value}\"",
                                StringTemplateArgumentPart part => $"{part.Name.ToCamelCase()}",
                                _ => throw new NotSupportedException(
                                    $"Template part of type '{templatePart.GetType().Name}' is not supported."
                                ),
                            };

                            cb.AppendLineIndented($"{str}{(isLast ? "" : ",")}");
                        }
                        cb.AppendLine($"),");
                        foreach (var argument in arguments)
                            cb.AppendLine($"{argument.Name} = {argument.Name.ToCamelCase()},");
                    }
                }
            }
        }

        context.AddSource($"{errorType.ToDisplayString()}.g.cs", cb.ToString());
    }
}
