using System;

namespace Base16.ErrGen.ErrorTypes;

internal static class StaticTypes
{
    public const String ErrorAttribute = """
        // <auto-generated/>
        #nullable enable

        namespace Base16.ErrGen;

        /// <summary>
        ///     Marks a partial record or record struct as a generated error type with a message template.
        ///     The generator produces a <c>Message</c> property, typed properties for each placeholder,
        ///     and static factory methods to construct instances.
        ///     <para>
        ///         Apply multiple times to generate multiple factory methods on the same type.
        ///     </para>
        /// </summary>
        /// <remarks>
        ///     <para>
        ///         Templates use <c>{Name}</c> for untyped (<see cref="object"/>?) arguments
        ///         or <c>{Name:Type}</c> for typed arguments.
        ///     </para>
        ///     <para>
        ///         Factory method names are derived from the placeholder names:
        ///         a single argument produces <c>FromName</c>,
        ///         multiple arguments produce <c>FromFirstSecondAndThird</c>.
        ///     </para>
        /// </remarks>
        /// <example>
        /// <code>
        /// // Single typed argument → FromStatusCode(Int32 statusCode)
        /// [Error("Request failed with status code {StatusCode:Int32}")]
        /// public partial record struct HttpError;
        ///
        /// // Multiple factory methods on one type
        /// [Error("Connection to '{Host:String}' timed out after {TimeoutMs:Int32}ms")]
        /// [Error("Connection to '{Host:String}' was refused")]
        /// public partial record struct ConnectionError;
        /// </code>
        /// </example>
        #pragma warning disable CS9113 // Parameter is unread.
        [System.AttributeUsage(System.AttributeTargets.Struct | System.AttributeTargets.Class, AllowMultiple = true)]
        public sealed class ErrorAttribute : System.Attribute
        {
            /// <summary>
            ///     The message template string.
            ///     Use <c>{Name}</c> for untyped arguments or <c>{Name:Type}</c> for typed arguments.
            /// </summary>
            /// <example>
            /// <code>
            /// "User '{Name:String}' was not found"
            /// "Field '{FieldName:String}' must be between {Min:Int32} and {Max:Int32}"
            /// </code>
            /// </example>
            public System.String Template { get; }

            /// <summary>
            ///     Initializes a new <see cref="ErrorAttribute"/> with the specified message template.
            /// </summary>
            /// <param name="template">
            ///     The message template. Use <c>{Name}</c> or <c>{Name:Type}</c> placeholders.
            /// </param>
            public ErrorAttribute(System.String template)
            {
                Template = template;
            }
        }
        #pragma warning restore CS9113 // Parameter is unread.
        """;

    public const String ErrorBaseTypeAttribute = """
        // <auto-generated/>
        #nullable enable

        namespace Base16.ErrGen;

        /// <summary>
        ///     Assembly-level attribute that configures a base type for all generated error types.
        ///     The base type can be an interface or a class (including abstract records with positional parameters).
        ///     <para>
        ///         If the base type declares a <c>String Message</c> property, the generator will not
        ///         re-generate it on the error types.
        ///     </para>
        ///     <para>
        ///         Individual error records can override this by declaring a base type directly
        ///         (e.g. <c>public partial record MyError : SpecificBase;</c>).
        ///     </para>
        /// </summary>
        /// <remarks>
        ///     <para>
        ///         Interfaces work with both record structs and record classes.
        ///         Classes work with record classes only — record structs cannot inherit from classes.
        ///     </para>
        ///     <para>
        ///         Abstract records with positional parameters (e.g. <c>record Error(String Message)</c>)
        ///         are supported. The generator chains the generated constructor to the base constructor
        ///         automatically. Non-Message constructor parameters are included as the first parameters
        ///         in all factory methods.
        ///     </para>
        /// </remarks>
        /// <example>
        /// <code>
        /// // Interface base type
        /// public interface IError { String Message { get; } }
        /// [assembly: ErrorBaseType(typeof(IError))]
        ///
        /// // Abstract record base type with constructor chaining
        /// public abstract record Error(String Message);
        /// [assembly: ErrorBaseType(typeof(Error))]
        ///
        /// // Abstract record with extra constructor parameters
        /// public abstract record TracedError(String Message, Guid TraceId) : Error(Message);
        /// [assembly: ErrorBaseType(typeof(TracedError))]
        /// // Factory methods will include TraceId as the first parameter
        /// </code>
        /// </example>
        #pragma warning disable CS9113 // Parameter is unread.
        [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple = false)]
        public sealed class ErrorBaseTypeAttribute : System.Attribute
        {
            /// <summary>
            ///     The base type (interface or class) that all generated error types will inherit from.
            /// </summary>
            public System.Type Type { get; }

            /// <summary>
            ///     Initializes a new <see cref="ErrorBaseTypeAttribute"/> with the specified base type.
            /// </summary>
            /// <param name="type">
            ///     The base type to inherit from. Must be an interface or a class (not a struct, enum, or generic type).
            /// </param>
            public ErrorBaseTypeAttribute(System.Type type)
            {
                Type = type;
            }
        }
        #pragma warning restore CS9113 // Parameter is unread.
        """;
}
